trigger: none

pr:
  branches:
    include:
    - '*'

pool: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci env:* | sort-object name | Format-Table -Property name,value -AutoSize'

- script: git diff --name-only HEAD^^ HEAD
  displayName: 'diffs'

- script: |
    set
    echo
    git diff --name-only origin/%SYSTEM_PULLREQUEST_TARGETBRANCH%
  displayName: 'pr diffs'