pr:
- master

pool: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci env:* | sort-object name | Format-Table -Property name,value -AutoSize'

- script: git diff --name-only HEAD^^ HEAD
  displayName: 'diffs'

- script: |
    echo %SYSTEM_PULLREQUEST_SOURCECOMMITID%
    git diff --name-only HEAD %SYSTEM_PULLREQUEST_SOURCECOMMITID%
  displayName: 'pr diffs'